/*
 * DOCSMOREAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DOCSMOREAPI.PCL;
using DOCSMOREAPI.PCL.Utilities;


namespace DOCSMOREAPI.PCL.Models
{
    public class DocumentFlowCollectionResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private string flowName;
        private object userid;
        private string primaryKey;
        private string firstNameKey;
        private string lastNameKey;
        private string apikey;
        private string createdOn;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("flowName")]
        public string FlowName 
        { 
            get 
            {
                return this.flowName; 
            } 
            set 
            {
                this.flowName = value;
                onPropertyChanged("FlowName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("userid")]
        public object Userid 
        { 
            get 
            {
                return this.userid; 
            } 
            set 
            {
                this.userid = value;
                onPropertyChanged("Userid");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("primaryKey")]
        public string PrimaryKey 
        { 
            get 
            {
                return this.primaryKey; 
            } 
            set 
            {
                this.primaryKey = value;
                onPropertyChanged("PrimaryKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("firstNameKey")]
        public string FirstNameKey 
        { 
            get 
            {
                return this.firstNameKey; 
            } 
            set 
            {
                this.firstNameKey = value;
                onPropertyChanged("FirstNameKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lastNameKey")]
        public string LastNameKey 
        { 
            get 
            {
                return this.lastNameKey; 
            } 
            set 
            {
                this.lastNameKey = value;
                onPropertyChanged("LastNameKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("apikey")]
        public string Apikey 
        { 
            get 
            {
                return this.apikey; 
            } 
            set 
            {
                this.apikey = value;
                onPropertyChanged("Apikey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createdOn")]
        public string CreatedOn 
        { 
            get 
            {
                return this.createdOn; 
            } 
            set 
            {
                this.createdOn = value;
                onPropertyChanged("CreatedOn");
            }
        }
    }
} 