/*
 * DOCSMOREAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DOCSMOREAPI.PCL;
using DOCSMOREAPI.PCL.Utilities;


namespace DOCSMOREAPI.PCL.Models
{
    public class GetAuthTOKENRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string apiKey;
        private string clientSecret;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("apiKey")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientSecret")]
        public string ClientSecret 
        { 
            get 
            {
                return this.clientSecret; 
            } 
            set 
            {
                this.clientSecret = value;
                onPropertyChanged("ClientSecret");
            }
        }
    }
} 