/*
 * DOCSMOREAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DOCSMOREAPI.PCL;
using DOCSMOREAPI.PCL.Utilities;


namespace DOCSMOREAPI.PCL.Models
{
    public class GetAuthTOKENResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string accessToken;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken 
        { 
            get 
            {
                return this.accessToken; 
            } 
            set 
            {
                this.accessToken = value;
                onPropertyChanged("AccessToken");
            }
        }
    }
} 