/*
 * DOCSMOREAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using DOCSMOREAPI.PCL.Controllers;
using DOCSMOREAPI.PCL.Http.Client;
using DOCSMOREAPI.PCL.Utilities;

namespace DOCSMOREAPI.PCL
{
    public partial class DOCSMOREAPIClient
    {

        /// <summary>
        /// Singleton access to GetAnAccessToken controller
        /// </summary>
        public GetAnAccessTokenController GetAnAccessToken
        {
            get
            {
                return GetAnAccessTokenController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to DOCUMENTFLOWS controller
        /// </summary>
        public DOCUMENTFLOWSController DOCUMENTFLOWS
        {
            get
            {
                return DOCUMENTFLOWSController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public DOCSMOREAPIClient() { }
        #endregion
    }
}