/*
 * DOCSMOREAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using DOCSMOREAPI.PCL;
using DOCSMOREAPI.PCL.Utilities; 
using DOCSMOREAPI.PCL.Http.Client;
using DOCSMOREAPI.PCL.Http.Response;
using DOCSMOREAPI.Tests.Helpers;
using NUnit.Framework;
using DOCSMOREAPI.PCL;
using DOCSMOREAPI.PCL.Controllers;
using DOCSMOREAPI.PCL.Exceptions;

namespace DOCSMOREAPI.Tests
{
    [TestFixture]
    public class GetAnAccessTokenControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static GetAnAccessTokenController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().GetAnAccessToken;
        }

        /// <summary>
        /// Make sure you call this in server side code. Exposing apiKey and clientSecret is a not a good idea on front end. 
        /// </summary>
        [Test]
        public async Task TestGetAuthTOKEN11() 
        {
            // Parameters for the API call
            PCL.Models.GetAuthTOKENRequest body = APIHelper.JsonDeserialize<PCL.Models.GetAuthTOKENRequest>("{    \"apiKey\": \"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\",    \"clientSecret\": \"XXXXXXXXXXXXX\"}");

            // Perform API call
            PCL.Models.GetAuthTOKENResponse result = null;

            try
            {
                result = await controller.CreateGetAuthTOKENAsync(body);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{    \"access_token\": \"eyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

    }
}